### ISSUE TITLE
Figure out logic for implicit parent categories

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#104]
New the "Categories" system is a two-level hierarchy with parent categories and subcategories. Many organizations will be tagged with one or more specific subcategories, with the intention that it is not necessary to also tag the parent. As a result, we need some logic on the code side to include these parents in our data for display and filtering.

The process will look like:
* For each organization
  * For each assigned category
    * If the category is a subcategory
    * And the parent category is not already assigned
      * Assign the parent category to the organization

**Comment by jasonLaster** [comment]
I'm not sure what you're getting at here

**Comment by bloudermilk** [comment]
@jasonLaster this was a note to properly handle primary/secondary categories. You already took care of it :)
