### ISSUE TITLE
[data] iron roots

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#114]
Iron Roots is missing a linked in profile, but it seems to exist here

https://www.linkedin.com/company/ironroots/

The linkedin profiles table, missing records view is empty, which makes me wonder how we missed it and perhaps other orgs like it?

**Comment by bloudermilk** [comment]
@jasonLaster we're missing a ton of LinkedIn Profiles right now for one of two reasons:

* We don't know the profile URL
* Nobody has scraped it yet

I'm hoping to do another big pass at some point. If you want to see all the orgs we don't have profiles for, [this view](https://airtable.com/tblPH0ZgLZYGVEhEo/viw9RmZyIK67JWvy1?blocks=hide) is where you want to look.
