### ISSUE TITLE
Re-evaluate use of web fonts

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#117]
What was wrong with the old font family that used modern system fonts across all platforms? The recent design changes introduced Roboto everywhere and embeds the font as base64 using a deprecated library.

**Comment by jasonLaster** [comment]
I have not noticed any issues with roboto so far... I'm fine closing this

**Comment by bloudermilk** [comment]
@jasonLaster this is still on my list to look into. We're missing font weights right now and I'd be happier to use system fonts to avoid the bloat. Let's keep it open for now

**Comment by jasonLaster** [comment]
I'm seeing this issue with 'Roboto Mono' in the climatescape title in the new navbar designs

**Comment by RNR1** [comment]
p.s when i tried changing the standards on tailwind config file i noticed that it also overwrites other standards related to that one(ex. i tried changing the "text-xs" and other "text-md" got affected.)
i am also noticed that there is a configuration of font-family's on that file, maybe it's related to that issue?
