### ISSUE TITLE
Simplify graphql queries

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#118]
The queries have become quite complicated:

- organizations have 2 queries for top and sub categories
- there's a lot of duplication

**Comment by jasonLaster** [comment]
We're working on a gatsby transformer that would inject parent categories on organizations before query time, allowing us to do this. Until then though, we could achieve both of the things you're wondering about:

* The query engine is based on [sift](https://www.npmjs.com/package/sift), which supports the `$or` operator
* Fragments work in Gatsby as well: [Using GraphQL Fragments in Gatsby](https://www.gatsbyjs.org/docs/using-graphql-fragments/)

**Comment by bloudermilk** [comment]
For posterity, it turns out Gatsby doesn't include the `$or` operator from sift, so fragments are the better route for now.
