### ISSUE TITLE
Organization pages

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#13]
Today we only show organizations in a list by sector. As we increase data points we'll probably want each record to have its own page. This would improve our UX by enabling users to link to specific organizations. It would also help our SEO a lot.

Information we should show:

* Name of the organization (large)
* Logo
* Tagline (large-ish)
* About (should probably hide if same as tagline, which is sometimes the case)
* External Links
  * Homepage
  * LinkedIn
  * Twitter
* Sector (link back to sector page?)
* List of tags
* Metadata
  * headcount
  * HQ location
  * organization type
* "Suggest Edit" button (URL TBD)
* Some kind of organization specific `<SEO>` content
  * Title should probably include the organization's name
  * Tagline could be useful in the description, with some other copy about Climatescape

**Comment by cyrilf** [comment]
Current status from #39 

- [x] Name of the organization (large)
- [x] Logo
- [x] Tagline (large-ish)
- [x] About (should probably hide if same as tagline, which is sometimes the case)
- [x] External Links
  - [x] Homepage
  - [x] LinkedIn
  - [x] Twitter
- [x] Sector (link back to sector page?)
- [x] List of tags
- [x] Metadata
  - [x] headcount
  - [x] HQ location
  - [x] organization type
- [ ] "Suggest Edit" button (URL TBD)  **Suggest Edit**
- [x] Some kind of organization specific <SEO> content
  - [x] Title should probably include the organization's name **SEO Title**
  - [x] Tagline could be useful in the description, with some other copy about Climatescape **SEO description**

----

-  **Suggest Edit**
  I don't know enough about airtable but does it support such a "edit form" feature that we could use/point to?

-  **SEO Title**
  For now I went for: `{ORGANIZATION_NAME} is solving climate change - Climatescape`.

- **SEO description**
  For now I went for: `{ORGANIZATION_NAME} is on Climatescape. {ORGANIZATION.TAGLINE}`

Let me know if you have a better idea for the SEO tags.

**Comment by bloudermilk** [comment]
Closing this–thank you @cyrilf !!!
