### ISSUE TITLE
We should let users filter by sub category, location, ...

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#132]
It should be easy to filter by sub category, location, stage, etc...

<img width="532" alt="Screen Shot 2020-03-24 at 9 27 14 AM" src="https://user-images.githubusercontent.com/254562/77451422-e2353c00-6db1-11ea-9d4f-b470ac40b8ca.png">

**Comment by bloudermilk** [comment]
The fields that we can reliably filter on today for the Organizations table are:

* Organization Type
* Role
* Categories (this would probably be restricted to subcategories given our sidebar)
* Headcount

Hopefully soon we will also have **Location** but there is backend work blocking this for now.

The "Capital" page should have a different set of filters, which mostly come from the "Capital Profiles" table:

* Organization Type
* Categories (It's unclear if we use the same sidebar+filter UX as the other orgs, as most investors are broad)
* Capital Type
* Check Size
* Stage
* Impact Specific
* Strategic

**Comment by miriambudayr** [comment]
Currently working on this 👍

**Comment by bloudermilk** [comment]
🔥
