### ISSUE TITLE
We should top-align the organization description

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#133]
I just noticed this inconsistency between the design and what we have:

---

<img width="1034" alt="Screen Shot 2020-03-24 at 9 30 56 AM" src="https://user-images.githubusercontent.com/254562/77451797-625ba180-6db2-11ea-9fd0-20f1d3318d33.png">

---

<img width="518" alt="Screen Shot 2020-03-24 at 9 32 40 AM" src="https://user-images.githubusercontent.com/254562/77451841-72738100-6db2-11ea-9b02-be6e18e9afc4.png">

**Comment by bloudermilk** [comment]
This is now implemented
