### ISSUE TITLE
SEO and OpenGraph meta tags

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#14]
To improve social sharing and search engine rank, we should implement helpful meta tags for each page. We already have react-helmet set up in the project and an `SEO` component which may be a good start. The work here is primarily generating the right content.

**Comment by nicolasca** [comment]
After a click on "Contribute" on the website I arrive here ^^.
I had a look at the seo component, and saw a dozen of meta tags already.
Do you know what kind of tags missing or the content to be replaced?

**Comment by bloudermilk** [comment]
@nicolasca ah, good catch. I ended up knocking a really basic version of this issue out last night ahead of the product hunt launch :) I'm going to close this issue and respond to your email. We could definitely use your help elsewhere!
