### ISSUE TITLE
Add an organization carousel

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#144]
At the moment we only show the first image, it would be nice to show all via a carousel

https://climatescape.org/organizations/arrival

I'm a big fan of airtable's fancy carousel -- https://airtable.com/shrbEdONg9Mmp2Tnf

it'd be neat if we could implement that.

**Comment by bloudermilk** [comment]
:thumbsup: Airtable's carousel is very sexy

**Comment by loiclefloch** [comment]
I would love to work on that :)

**Comment by bloudermilk** [comment]
@loiclefloch all yours!
