### ISSUE TITLE
Simplify the navbar

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#146]
We're working on a new header structure and brand here

https://www.figma.com/file/8iR5eO5wK6s2WIFhm4o9Hl/Climatescape-Logo?node-id=0%3A1
https://www.figma.com/file/GvYYLhGvEsLxS1T677r0Ox/Climatescape?node-id=125%3A12045

**Comment by bloudermilk** [comment]
@jasonLaster I think you achieved this?
