### ISSUE TITLE
Fix Brainbox AI image

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#149]
Something weird is going on with the Brainbox AI

<img width="1220" alt="Screen Shot 2020-03-25 at 5 39 32 PM" src="https://user-images.githubusercontent.com/254562/77598669-a6889800-6ebf-11ea-899d-43dca3a039b0.png">

**Comment by bloudermilk** [comment]
Fixed by removing the image, which looked to be a strange hack to animate something
