### ISSUE TITLE
The entire OrganizationCard component should be a Link

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#156]
We should wrap the entire `OrganizationCard` component in a `Link` rather than only the logo and name of an organization being clickable. We should keep in mind the following:

* We can take hover styles off of the `{title}`
* We should add a hover style to the entire card
  * darker grey background color
  * cursor: pointer

---

Old description:

~~It would be nice to conceptually treat the organization row as a card that can be clicked. At the moment, just the title and image navigate to the organization page.~~

~~Note, we'll want to still have the tags be clickable, but i think that is common with other types of cards.~~

**Comment by bloudermilk** [comment]
👍 on this. My thought is that once we have the top-bar filters in, we should take out the clickable tags and find a better way to display that info anyway. So it would avoid the link-in-link UX issue.
