### ISSUE TITLE
[Capital] Add capital type categories

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#160]
It would be nice if i could how many angels, vcs, and incubators were in the list. I think that is fairly comparable to our org categories

**Comment by jasonLaster** [comment]
![capital-cats](https://user-images.githubusercontent.com/254562/77785465-75bc7600-7019-11ea-96df-cc1491a4e8bf.png)

**Comment by bloudermilk** [comment]
I like this a lot. We'll want to consider how we present each of the capital types:

* Venture Capital
* Project Finance
* Private Equity
* Incubator
* Accelerator
* Grants

**Comment by candlergrimes** [comment]
Love this idea. Agreed with @bloudermilk. Feels like there are a few capital types: 
- Venture Equity
- Non-dilutive capital (Grants, Prizes)
- Project FInance
- Debt

Each org could provide one or more of these. 

Separately, we'll see some overlap with the standard orgs. I'm particularly thinking of Incubators / Accelerators that provide Advocacy, Networking, Grants, Prizes and Equity Capital. 

At this point, I'm not well versed enough on the data model to propose a solution. Just putting my thoughts here.

**Comment by bloudermilk** [comment]
This was implemented by @jasonLaster
