### ISSUE TITLE
[content] Jupiter description is weird

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#162]
Jupiter's description is one word

https://climatescape.org/organizations/jupiter-intelligence

**Comment by bloudermilk** [comment]
@jasonLaster fixed this:

> Jupiter provides data and analytics services to better predict and manage risks from weather and sea level rise, storm intensification and changing temperatures caused by medium- to long-term climate change. 

> Offices in: Silicon Valley, Boulder, CO & New York Metro areas

Will go out in next auto deploy
