### ISSUE TITLE
Add a link to our slack

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#166]
It would be great to invite folks to join our slack. One of the easiest ways to do that is to add a slack invite link to the site, perhaps in the footer.

**Comment by soniasingla** [comment]
Can I take this issue? :)

**Comment by bloudermilk** [comment]
@soniasingla we're actually going to hold off on this for now. We need to figure out some onboarding process things first

**Comment by soniasingla** [comment]
Sure ! Thanks for the information.

**Comment by bloudermilk** [comment]
#170 would be a great frontend issue to work on if you're interested

**Comment by RNR1** [comment]
this one lays here for a while, just pinging to see if it's still relevant or you should close it :)

**Comment by bloudermilk** [comment]
@RNR1 we can close this for now. We're still working out how to best organize new additions to the editorial team
