### ISSUE TITLE
Improve our 404 page

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#168]
We get a fair bit of 404's for organizations we've removed or renamed. Would be great to have a better looking and more helpful 404 page to guide these visitors.

Example: https://climatescape.org/organizations/climateneutral

At the very least a minimal design would improve the experience. Ideally some copy to instruct visitors how to search in case their org just got renamed.

**Comment by RNR1** [comment]
is this one should be closed?

**Comment by bloudermilk** [comment]
@RNR1 yup!
