### ISSUE TITLE
Unified activity feeds per category or tag

### ISSUE THREAD

**Issue by leventov** [climatescape/climatescape.org#175]
We can try to combine together all twitter, youtube, news, blogs, etc. feeds from all companies in a category or a tag and present them together. This may be a way for people to track news/updates in their field of interest.

See also #57

**Comment by bloudermilk** [comment]
This has come up a few times and I personally see limited value in it. I think we're opening up a big can of worms here for limited value. Most social posts from companies tend to be low quality and self-promoting in nature. I think if users really want to see social streams from some orgs, they should just follow those orgs on their platform of choice.

How could we rethink this to focus on important updates? How could we simplify the implementation to avoid having to query/store/render all these different social & news streams? What kind of updates are people actually interested in?
