### ISSUE TITLE
Add a link for all organizations

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#193]
We should make it clear that there is an option for viewing all of the organizations

https://climatescape.org/organizations/

<img width="622" alt="Screen Shot 2020-03-31 at 1 01 32 PM" src="https://user-images.githubusercontent.com/142254/78019322-c8669c80-734f-11ea-98ae-babd0951302b.png">

**Comment by RNR1** [comment]
isn't it the one i implemented already?
