### ISSUE TITLE
Restyle org tags and links

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#204]
The new organization page has a simplified UI for tags and links, that is a lot cleaner. It would be great to implement that.

![org-view](https://user-images.githubusercontent.com/254562/78171773-d37e0300-7409-11ea-9ec3-2105b94a8c09.png)

**Comment by loiclefloch** [comment]
I will work on it tonight :)

**Comment by RNR1** [comment]
i opened a PR, me and @loiclefloch handled that issue, it's not responsive yet but the rest of the design is there.
