### ISSUE TITLE
We should show the twitter handle

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#210]
Instead of showing the twitter icon and Twitter label, we should parse the Url to show the twitter domain

We could do it with something like this

```
export function parseTwitterPath(url) {
  if (!url) return null
  const displayName = new URL(url).pathname.substring(1)
  return `@${displayName}`
}
```

**Comment by jasonLaster** [comment]
<img width="472" alt="Screen Shot 2020-04-02 at 4 14 22 PM" src="https://user-images.githubusercontent.com/254562/78308416-42885400-74fd-11ea-8c21-a55b58cda138.png">

**Comment by solnsubuga** [comment]
@jasonLaster I would love to work on this issue and get started contributing.

**Comment by bloudermilk** [comment]
@solnsubuga I just invited you to our team Slack and Airtable. The `README` should contain all the info you need to get your environment set up, but ping us in the #development channel once you're online and we can help you out if you have any trouble :)

**Comment by bloudermilk** [comment]
looks like someone already took care of this issue
