### ISSUE TITLE
Fall back to logos from Crunchbase

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#216]
We should update `getLogo` in `airtable.js` to check for a `Logo` attachment in the "Crunchbase ODM" table. GraphQL queries using this function (`OrganizationCard` and `templates/organization.js`) should use the same `OrganizationCardPhoto`. Order of precedence should be:

1. `Logo` on `Organizations`
2. `Logo` on `LinkedIn Profiles`
3. `Logo` on `Crunchbase ODM`

**Comment by jasonLaster** [comment]
Happy to do this in a bit

**Comment by bloudermilk** [comment]
@jasonLaster implemented this. Closing
