### ISSUE TITLE
Implement search capabilities

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#22]
Several people have asked for the ability to search the database, which I think is a great idea. Especially useful to see if an org is already listed.

I know [Algolia](https://www.algolia.com/) works with statically generated sites, but there may be other solutions.

**Note:** this is likely dependent on organization pages. Currently we only have organizations listed in sector pages.

**Comment by jasonLaster** [comment]
I'd be happy to take a look. The simplest solution would be something like https://fusejs.io/, but Algolia could likely be a better solution.

**Comment by jasonLaster** [comment]
This issue can be focused on text search, but big picture I think it would be nice to have more general search tools focused on as many columns as possible.

Angellist does a good job of this:

<img width="1076" alt="Screen Shot 2020-02-07 at 9 49 29 AM" src="https://user-images.githubusercontent.com/254562/74052655-306fb680-498f-11ea-8563-8b87fa7c7fd1.png">


<img width="1123" alt="Screen Shot 2020-02-07 at 9 51 20 AM" src="https://user-images.githubusercontent.com/254562/74052818-73ca2500-498f-11ea-94fd-90fb1435c11f.png">

**Comment by jasonLaster** [comment]
As a reference, I'm thinking of using tailwind components and  https://react-select.com/home

**Comment by jasonLaster** [comment]
We likely want to separate out a couple of tasks here:

1. better filtering
2. a global search bar

**Comment by bloudermilk** [comment]
Closing this with the search functionality implemented by @jasonLaster in #62. We'll break out filtering into its own issue.
