### ISSUE TITLE
Crunchbase Enrichment should only use .jpg/.jpeg/.png files

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#220]
Several organizations have logos that are not compatible with our image processor. Including:

* Files without an extension
* `gif` and `bmp` files

We should update the Crunchbase enrichment script to whitelist logos that have one of the following extensions: `.jpg`, `.jpeg`, `.png`

**Comment by bloudermilk** [comment]
Fixed the problematic logos and updated the description to be clearer about the change that needs to happen.
