### ISSUE TITLE
Show capital types on the homepage

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#223]
It'd be great to show the various capital types on the homepage.

To do this we'll also need unsplash images for all of them, or go with a different approach, but i think the images are a nice visual way of showing categories :)

also, it is a nice fallback for capital logos on the list page...

- Venture Capital
- Project Finance
- Private Equity
- Incubator
- Accelerator
- Grant
- Prize
- Angel

**Comment by bloudermilk** [comment]
Closed by #225
