### ISSUE TITLE
The autocomplete highlight should be more subtle

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#224]
The highlight is currently a yellow background. It used to be bold text with no background, which was a bit cleaner.

<img width="688" alt="Screen Shot 2020-04-03 at 9 16 20 PM" src="https://user-images.githubusercontent.com/254562/78418380-6d070980-75f0-11ea-8781-b92736ab2ae0.png">

**Comment by chenxsan** [comment]
Not sure what's going on here, but this rule https://github.com/climatescape/climatescape.org/blob/4da4ff889b6228d378b2c3ef50f0b03ac95e39ca/src/components/search/styles.css#L26 is missing in production:

![image](https://user-images.githubusercontent.com/1091472/78449915-48249c00-76ad-11ea-97a7-24cb7f065e73.png)

**Comment by bloudermilk** [comment]
@chenxsan I think we could simply add that class to our CSS and set a more reasonable highlight color. `blue-400` or something (just pulled that out of the air). Want to tackle this?

**Comment by bloudermilk** [comment]
Closed by #231
