### ISSUE TITLE
Fix headcount for "Hyperloop One"

### ISSUE THREAD

**Issue by miriambudayr** [climatescape/climatescape.org#233]
I noticed this company's headcount isn't a real range.

![Screen Shot 2020-04-06 at 11 28 31 AM](https://user-images.githubusercontent.com/35577323/78581647-c3936400-77f9-11ea-9ce4-c86bf1dec599.png)

**Comment by bloudermilk** [comment]
Good find, just fixed this. Your dev environment should pick up the change immediately. It'll go out during our next production deploy as well.
