### ISSUE TITLE
Add a "Contributors" or "Team" section

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#24]
I'd love to give credit to those who have contributed code or content. Maybe we could include their:

* Name
* Avatar
* Link
* Contribution(s)

**Comment by cyrilf** [comment]
There is an [existing spec called "All contibutors"](https://allcontributors.org/) to add Contributors to the README / website.

**Comment by bloudermilk** [comment]
@cyrilf that's really cool–I'll make a note to integrate it. I still think it would be good to have a contributors section on the site so we can give everyone credit, even if they're not contributing code. @lloudermilk is going to start working on that today 🎉
