### ISSUE TITLE
Hide "In a snapshot" section when we have no metadata

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#242]
Example: https://climatescape.org/organizations/ann-bordetskyreport

<img width="216" alt="Screen Shot 2020-04-07 at 2 40 37 PM" src="https://user-images.githubusercontent.com/142254/78670302-d4b5a100-78dd-11ea-8587-c0459da8270d.png">

**Comment by RNR1** [comment]
i am currently on these menus so i will fix it as well

**Comment by bloudermilk** [comment]
Excellent, thanks @RNR1 !
