### ISSUE TITLE
Categories should be links in "IN A SNAPSHOT" section

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#250]
On the organization page, we list the categories it is filed under under "IN A SNAPSHOT". We have pages for all these categories, and should make them links to go back to the respective page.

<img width="292" alt="Screen Shot 2020-04-08 at 10 43 53 AM" src="https://user-images.githubusercontent.com/142254/78763867-0124f800-7986-11ea-89bc-bf320172ccae.png">

In the example above, "Food & Agriculture" should be a `Link` to that category.

**Comment by RNR1** [comment]
great idea, i think i can take this

**Comment by bloudermilk** [comment]
@RNR1 that would be great!

**Comment by RNR1** [comment]
i found an issue with that feature, and i think that it might be need a change in the organisations list.
right now only the top categories has a path which responds. the sub-categories does not contain a path to it's filter so they lead to a 404.

**Comment by bloudermilk** [comment]
@RNR1 just merged a change that adds pages for these subcategories. Can you try rebasing master?

**Comment by RNR1** [comment]
great, i pulled the changes so i will rerun the environment and apply them after the merge

**Comment by RNR1** [comment]
submitted a few PRs, including this one^ :)

**Comment by bloudermilk** [comment]
Fixed by #254
