### ISSUE TITLE
[bug] Not all capital types on homepage have respective pages

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#270]
For example, [Fellowships](https://climatescape.org/capital/fellowships) on the homepage results in a 404. We maybe merged #260 too soon?

**Comment by bloudermilk** [comment]
@jasonLaster I think this is related to #260

**Comment by jasonLaster** [comment]
It should be fixed by https://github.com/climatescape/climatescape.org/pull/265 which will make sure these two things are in sync.

**Comment by bloudermilk** [comment]
@jasonLaster got it. Any idea why that's not passing CI or build? I can take a look tomorrow
