### ISSUE TITLE
Searching for company that doesn't exist sends to Algolia homepage

### ISSUE THREAD

**Issue by candlergrimes** [climatescape/climatescape.org#273]
When I hit ENTER and there are no valid entities in the quick-search results dropdown (see: example image), I am taken to algolia.com.

While not a huge deal, this feels jarring. Took me some digging to figure out what happened. 

In my mind, I would expect to be taken to a search results page with either (1) no results or (2) similar results. Other options would be to (3) do nothing when clicking enter OR (4) having a signal indicating I have selected Algolia. 

![image](https://user-images.githubusercontent.com/37845867/79594564-14287e00-8092-11ea-9dc1-0bdbadf4d825.png)

**Comment by bloudermilk** [comment]
@candlergrimes thanks for filing this. What a strange issue!
