### ISSUE TITLE
Backend for managing Lists

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#281]
The backend should allow for the following behaviors to start:

* One list named "Favorites" should be auto-created for each user
* Authenticated users should be able to add items from their list
* Authenticated users should be able to remove items from their list
* Unauthenticated users should be able to view other user's lists

### Lists

* `id`
* `user_id`
* `name`
* `created_at`, `updated_at`

### List Organizations

* `id`
* `list_id`
* `organization_id`
* `created_at`, `updated_at`

**Comment by miriambudayr** [comment]
@bloudermilk 

I set up schemas for lists and added a rule in the Auth0 "Rules" section to automatically add a "Favorite" list to the new user. I can comment it out for the favorites MVP if you want to turn it off for now though.
