### ISSUE TITLE
Source: 100 smart city startups

### ISSUE THREAD

**Issue by leventov** [climatescape/climatescape.org#30]
https://www.cbinsights.com/research/smart-city-startups-market-map/. Could somebody with a "business" e-mail download the report and attach it here?

**Comment by lb-** [comment]
Here is the html for the table, have not yet converted to CSV. Contains ~500 companies from that list, includes company name, website and total funding.


[table.html.zip](https://github.com/bloudermilk/climatescape/files/4082356/table.html.zip)

**Comment by lb-** [comment]
Here is the data parsed to JSON & CSV - zip file attached.

[data.zip](https://github.com/climatescape/climatescape.org/files/4114564/data.zip)

Note: Image URLs are at cbinsights and may need to be further processed/re-downloaded.

JS code used on the html file...

```javascript
JSON.stringify(Array.from(document.querySelectorAll('tbody > tr')).map(element => {

  const description = element.querySelector('[data-test="itemDetails"]').innerHTML;
  const image = (element.querySelector('[data-test="company-photo"] > img') || {}).src;
  const name = element.querySelector('[data-test="entityName"] > a').text;
  const tags = (Array.from(element.querySelectorAll('[data-test="tag-td"] > ul > li > a')) || []).map(el => el.text.replace('#', ''));
  const websiteUrl = (element.querySelector('[data-test="goto-company-website"]') || {}).href;

  return {
    description,
    image,
    name,
    tags,
    websiteUrl,
  };
}))
```

**Comment by bloudermilk** [comment]
@lb- thanks for this! Much easier to process now. I think there is a good number of companies in there that would fit well on Climatescape, though most aren't necessarily climate related.

**Comment by bloudermilk** [comment]
@lb- we're moving our content management backlog to another tool so I'll be closing this issue. Just wanted to thank you sincerely for putting that zip together for us. It's incredible helpful! Shoot me an email if you'd like to join our content team and take on more projects like this: brendan {at} sinceresoftware {dot} co
