### ISSUE TITLE
Implement responsive Favoriting UI

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#303]
We currently hide the `FavoriteButton` globally on mobile devices. We should figure out how to include these in the design in a reasonable way.

**Comment by RNR1** [comment]
![Screen Shot 2020-06-17 at 11 05 07](https://user-images.githubusercontent.com/45559220/84872328-6aae3a80-b08a-11ea-8758-d25d57655350.png)
i aligned it to the start on small screens, let's start a topic
