### ISSUE TITLE
Add eslint-plugin-react-hooks to site

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#305]
Added protection to make sure we're using React Hooks right right way.

https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by RNR1** [comment]
from what i see in package.json we already have this. is this one relevant?

**Comment by RNR1** [comment]
just updating that i'm on it right now and there are a lot of work around this lint!
also i found some typos that i'm fixing on the way
