### ISSUE TITLE
Show category definition when present

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#308]
Some categories have a short description which is meant to be rendered on the category page. We should check for this `Definition` field and display it when possible.

<img width="987" alt="Screen Shot 2020-05-11 at 2 54 56 PM" src="https://user-images.githubusercontent.com/142254/81564108-87729680-9397-11ea-9103-e49b7dfc3ee5.png">

**Comment by RNR1** [comment]
hi! is it assigned to anyone? can i take it?

**Comment by bloudermilk** [comment]
This would be a great one to take on :) the field is already in AirTable
(Sean has provided copy for some categories)

**Comment by RNR1** [comment]
it's available on PR

**Comment by bloudermilk** [comment]
Excellent :) will take a look ASAP!
