### ISSUE TITLE
Vionx is duplicated in the orgs page, but not in airtable

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#316]
Sean noticed a duplicate record on the site that isn’t showing in Airtable: “Vionx” and “Vionx Energy”

<img width="548" alt="Screen Shot 2020-05-17 at 9 22 12 PM" src="https://user-images.githubusercontent.com/254562/82174139-81435500-9884-11ea-910e-1a9b32753411.png">

**Comment by bloudermilk** [comment]
Dug into this further and our Algolia plugin *should* remove records deleted from Airtable. Not sure how this one got out of sync but I did a full rebuild of our index and it seems to be fixed now.
