### ISSUE TITLE
Render metadata on organization lists

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#32]
We should show additional information that our DB now contains:

* logo - shown to the left of info
* tagline - prefer linked in, default to "About"
* location - need to experiment with this
* headcount - SVG icon with heads
* company type - should we include this?

**Comment by jamescrowley** [comment]
I'm working on this now :)

**Comment by bloudermilk** [comment]
@jamescrowley 🙌

**Comment by bloudermilk** [comment]
Done thanks to #34
