### ISSUE TITLE
Browse and filter not only by sector

### ISSUE THREAD

**Issue by nicolasca** [climatescape/climatescape.org#36]
Currently it is possible to browse the organizations by sector, and then apply filter tags to it, which is very useful.

It would be nice to: 

1/ to filter with a tag for all the organizations from all the sectors (not for each sector)

2/ I put here to not create another issue about search: would it be hard work to split the localization as a city and a country ? Because the tag filter by country alone would very much appreciated.

What do you think ?

**Comment by bloudermilk** [comment]
@nicolasca thanks for the feedback, you're spot on about both these issues. They're on our radar and we're doing some product planning out of GH right now, so I'm going to close this issue. Expect to see something similar come back soon :)
