### ISSUE TITLE
Adopt a component framework

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#50]
Adopting a component framework would give us a quick boost to have a lot of great looking UI components, and would help mike and @Juliana Vislova focus on things like layout, architecture, and brand. 

https://material-ui.com/

**Comment by jasonLaster** [comment]
Some other benefits include:

- responsive design
- figma library (https://www.figma.com/resources/assets/material-design-themeing-ui-kit/)

Open Questions:
- does this make it harder to develop custom components
- does this make it harder to differentiat
- are there other frameworks that make more sense

**Comment by jasonLaster** [comment]
Here is some more information on tailwind

https://tailwindcss.com/components/

and a link to the figma file -- https://www.figma.com/c/file/768809027799962739

**Comment by bloudermilk** [comment]
Tailwind now has a commercial component library: https://tailwindcomponents.com/

**Comment by jasonLaster** [comment]
👍 i wonder if there are any components we want to use.

At this point, i feel like we should stick with tailwind :)

**Comment by bloudermilk** [comment]
@jasonLaster I agree, Tailwind is working well for us and the design didn't end up using a component framework anyway, which was the main impetus for this
