### ISSUE TITLE
Import angellist companies and data

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#53]
Angellist has ~7,000 clean-technology companies that would be worth including.

They also have fields like startup stage, total raised, and investors which is interesting.

- https://angel.co/companies?markets[]=Clean+Technology
- https://angel.co/markets
- https://angel.co/clean-technology

```
copy(companies.map(c => ['.company', '.location', '.website', '.company_size', '.stage', '.raised', '.market' ].map(q => c.querySelector(q).innerText.trim()).join("\t") ).join("\n"))
```

**Comment by jasonLaster** [comment]
Angellist caps the number of companies shown at ~800, which means we'll likely want to loop over each market.

**Comment by bloudermilk** [comment]
@jasonLaster moving this to Notion
