### ISSUE TITLE
Hide draft organizations

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#59]
currently the `/organizations` shows all companies regardless of whether they're draft or published. We should add a filter to this list.

**Comment by cyrilf** [comment]
@jasonLaster isn't the `tableView` being `Published` in airtable already a sufficient filter?

(I don't have access to the new base, so maybe the new one is missing a filter on this view? :thinking: )

https://github.com/climatescape/climatescape.org/blob/279da2cfe458d60f5d01687e183d7d30a2358323
/gatsby-config.js#L27-L28

**Comment by cyrilf** [comment]
Btw @jasonLaster this applies to any sector page too.. :cry: 

https://climatescape.org/sectors/food-and-agriculture

**Comment by bloudermilk** [comment]
Mentioned this elsewhere, but it was intentional to show these organizations. Closing this for now but curious if there's a better way we can include in our backlog without making the site look awkward. For example, by moving them to the bottom of the list.
