### ISSUE TITLE
Source: Stanford TomKat Sustainability Companies

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#6]
https://tomkat.stanford.edu/sustainability-companies

**Comment by bloudermilk** [comment]
I reached out to Brian @ TomKat, who told us about this list on Slack. I asked him how he'd feel about us incorporating the data and will report back here with his response.

**Comment by haudarren** [comment]
I know him personally, so feel free to tell him I support it.  I imagine he'll be quite supportive.  We should also offer a way to embed this in his website so he doesn't have to maintain his own.  +1 for more adoption :)

**Comment by bloudermilk** [comment]
@haudarren would you be willing to reach out to Brian personally? I think he's no longer active on the MCJ Slack where I was talking to him.

**Comment by haudarren** [comment]
@bloudermilk I just spoke with him, and he's definitely onboard!  He's fine with us incorporating the data and linking/embedding the final product on the TomKat website.

**Comment by bloudermilk** [comment]
@haudarren amazing, thank you for getting in touch with him. Attaching a ZIP of CSV exports of all the sheets in that doc.

[Archive.zip](https://github.com/bloudermilk/climatescape/files/4081116/Archive.zip)

**Comment by bloudermilk** [comment]
@haudarren FYI moving our content management to another tool
