### ISSUE TITLE
Only update Algonia index for new/updated organizations

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#63]
We're currently updating every organization in our Algolia index each time we deploy (at least once daily). Each record in that process uses an "operation" from our quota, which wastes our somewhat limited free quota.

It would be better to only push organizations to Algolia when they're added or updated. This could be achieved with a timestamp and maybe tracking the time since last deploy.

**Comment by bloudermilk** [comment]
With the number of deploys we're doing these days this is becoming more and more important. We're burning through our allotted Alogolia usage quite fast.

**Comment by jasonLaster** [comment]
@bloudermilk i bet we can use a read only key, and move the re-builds to a daily GH action 

https://help.github.com/en/actions/reference/events-that-trigger-workflows

**Comment by bloudermilk** [comment]
@jasonLaster this is a great idea! I wonder if there is enough crossover to make this the same action that does our daily site builds, currently happening from a Zapier job.

**Comment by bloudermilk** [comment]
Did some more research here:

* There is a [PR](https://github.com/algolia/gatsby-plugin-algolia/pull/27) to add partial index updating to the Gatsby plugin, but it doesn't look like they will merge it.
* The author of that PR published [a fork](https://www.gatsbyjs.org/packages/gatsby-plugin-algolia-search/) of the plugin with this functionality.

Sidenote: if we end up adding this back to the site build process (via Netlify or GitHub) we should make sure it only runs for production builds, not branch/PR builds.
