### ISSUE TITLE
It should be possible to "Add organization" from the search results

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#64]
It would be nice if I could add an organization if i don't see a company in the search results list.

I think we could add another row above the "powered by algolia" footer...

**Comment by bloudermilk** [comment]
I don't think I agree with this from a UX perspective. We have clear CTAs for adding orgs around the site and it complicates the search UI for a pretty narrow case, in my opinion.

**Comment by bloudermilk** [comment]
We have several places to add organizations now that I believe this feature is not required.
