### ISSUE TITLE
Polish search dropdown ui

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#69]
- The dropdown should not have a scrollbar
- Results should be clipped so they stay on one line

<img width="598" alt="Screen Shot 2020-02-19 at 9 35 20 AM" src="https://user-images.githubusercontent.com/254562/74859106-3f455a00-52fb-11ea-866b-d0b66da896fc.png">

**Comment by loiclefloch** [comment]
@bloudermilk I think the recently merged PR regarding the search is fixing those issues:
- I have fixed the one line problem
- I do not see any scrollbar anymore

**Comment by jasonLaster** [comment]
good call

**Comment by jasonLaster** [comment]
One small thing: The highlighted section should be black and not yellow

<img width="530" alt="Screen Shot 2020-03-31 at 8 40 18 AM" src="https://user-images.githubusercontent.com/254562/78045864-4a909a00-732b-11ea-8de7-08fe84f56ea8.png">
