### ISSUE TITLE
Source: How to find a job in a tech company helping to combat climate change? 

### ISSUE THREAD

**Issue by bloudermilk** [climatescape/climatescape.org#9]
https://medium.com/@leventov/how-to-find-a-job-in-a-tech-company-helping-to-combat-climate-change-practical-guide-e212e262a32

**Comment by andreadellacorte** [comment]
Hey @bloudermilk would love to collaborate with you on this project; maybe this could be a good ticket for me to get started? What do you see as its outcome?

**Comment by bloudermilk** [comment]
@andreadellacorte thanks so much for offering to help! This is a great issue for you to get started on. We're looking for two outcomes on these types of issues:

* Any organizations that meet rule #1 in out [Content Guidelines](https://github.com/bloudermilk/climatescape/wiki/Content-Guidelines%3A-Organizations) can be added via the [Contribute page](https://climatescape.org/contribute/). For now that page accepts limited information, which one of our editors will add to once submitted.
* Any references to other lists like this one can be added as an issue for further processing. For example, there is a link on this Medium post which we would add as "Source: Europe’s top 30 cleantech startups (EIT Climate-KIS)", including the URL in the description of the issue.

I hope this is clear! Please let me know if you have any questions 😃

**Comment by bloudermilk** [comment]
@andreadellacorte just wanted to check in to see if you're still interested in helping out. We also have some good code-related issues if you'd prefer to pitch in that way. Cheers!

**Comment by andreadellacorte** [comment]
Hello! Yes, very interested in helping, thanks for the guidelines :)

I am going to take a broader look at all the issue and let you know when I get started (is there a way for me to assign the issue to myself, or will you do that for me?)

**Comment by bloudermilk** [comment]
@andreadellacorte assigned! Please let me know if there's anything I can do to help :)

**Comment by bloudermilk** [comment]
@andreadellacorte I'm closing this issue as we're moving the content management backlog to another tool. Let me know if you're still interested in collaborating–we have better tasks for new contributors: brendan {at} sinceresoftware {dot} co
