### ISSUE TITLE
we should import the climate accelerator list 

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#90]
https://airtable.com/shrLkcxSb7RZfpATq/tblWaB0q1IQvG7Stk?blocks=hide

**Comment by bloudermilk** [comment]
@jasonLaster we're tracking this in Notion, along with other bulk import jobs :)

**Comment by jasonLaster** [comment]
agreed. adding these for posterity

https://airtable.com/shrEQDpY99ohkTzIV/tblWaB0q1IQvG7Stk?blocks=hide
https://airtable.com/shrpoJ9cKDjdXEmt4/tblWaB0q1IQvG7Stk?blocks=hide
