### ISSUE TITLE
The search box crashes locally

### ISSUE THREAD

**Issue by jasonLaster** [climatescape/climatescape.org#93]
For some reason clicking on the search box locally starts an infinite loop...

Adding a logpoint in `http://localhost:8000/Users/jlaster/src/_os/climatescape.org/node_modules/fast-deep-equal/index.js:48`  shows that react will keep re-rendering because it thinks (incorrectly) that something changed.

For some reason, this is different in production. I am not sure why, but it is probably something to do with the data.

**Comment by bloudermilk** [comment]
@jasonLaster I'm unable to repro this locally. Could it be a configuration issue?
